---
zmdd1:
  vip: "1"
  prefix: false
  date: "2015-06-26"
  day: "1"
zmddqweqwe:
  vip: "3"
  prefix: false
  date: "2015-06-26"
  day: "1"
sapdjpoa:
  vip: "3"
  prefix: false
  date: "2015-06-26"
  day: "1"
ksajdlkajsd:
  vip: "3"
  prefix: false
  date: "2015-06-26"
  day: "1"
1234123:
  vip: "3"
  prefix: ""
  date: "2015-06-26"
  day: "1"
...
