---
#--------------------------------
language: "CN"
#--------------------------------
server_lobby_world: mcg76_blockhunt_home
server_lobby_x: "126"
server_lobby_y: "4"
server_lobby_z: "134"
blockhunt_home_world: mcg76_blockhunt_home
blockhunt_home_x: "126"
blockhunt_home_y: "4"
blockhunt_home_z: "134"
minimal_players_to_start: 2
server_lobby_sign_level: mcg76_blockhunt_home
server_lobby_sign_x: 125
server_lobby_sign_y: 5
server_lobby_sign_z: 121

#default teleport to lobby
default_teleport_player_to_lobby_on_join: true
...
